---
- name: "Download Kibana's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-x86_64.rpm"
    dest: "files/kibana-{{ elk_stack_version }}-x86_64.rpm"
  register: download_kibana
  until: download_kibana is succeeded